name: Deploy to github pages

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]

jobs:
    gh-pages-deploy:
        name: Deploying to gh-pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Clean install dependencies
              run: npm ci

            - name: Run deploy script
              run: |
                  git config user.name "anantmittal" && git config user.email "mittal.anant@gmail.com"
                  npm run gh-pages-deploy
